---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-deploy
  namespace: beer
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: git@github.com:arctiqtim/beer-giphy-deploy.git
