apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: pipeline-run-random-giphy-
  namespace: random-giphy
spec:
  pipelineRef:
    name: random-giphy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: git-source
    - name: git-deploy
      resourceRef:
        name: git-deploy
  params:
    - name: targetBranch
      value: "master"
    - name: imageTag
      value: "v1.3"
  serviceAccount: arctiqtim-git-ssh